#!/bin/bash

# opens all the files that have been modified (according to git status) in neovim

$(git status | awk 'BEGIN {command = "nvim ";} /modified/ {command = command " " $2;} END {print command}')
